//  Quick Look for the Ember file ecosystem.
//
//  Pressing space on a file in Finder should answer "what is this" without
//  opening it. That is the exact promise the SUMM chunk was designed to make
//  — §2.6 of the Wick spec calls it the tier a file browser reads instead of
//  the payload — so this extension is a thin shell around `hearth preview`,
//  which reads that tier and nothing else.
//
//  It is a *data-based* preview extension (QLIsDataBasedPreview), which means
//  it hands Quick Look bytes and a content type rather than a view hierarchy.
//  There is no UI to build here: the preview is HTML, generated by the same
//  code path a person can run in a terminal and read. A preview nobody can
//  reproduce outside the extension is a preview nobody can debug.

// On macOS the data-based preview classes live in QuickLookUI; the QuickLook
// framework itself is the old generator API that this replaces.
import Foundation
import QuickLookUI
import UniformTypeIdentifiers

@objc(PreviewProvider)
final class PreviewProvider: QLPreviewProvider, QLPreviewingController {

    // The callback form rather than the `async` one: it is the method the
    // protocol actually declares, and it does not depend on which Swift
    // concurrency back-deployment the host has.
    func providePreview(
        for request: QLFilePreviewRequest,
        completionHandler handler: @escaping (QLPreviewReply?, Error?) -> Void
    ) {
        let url = request.fileURL
        // The size is a hint for the pane, not a constraint on the content.
        let reply = QLPreviewReply(
            dataOfContentType: .html,
            contentSize: CGSize(width: 800, height: 900)
        ) { _ in
            try Self.preview(of: url)
        }
        reply.title = url.lastPathComponent
        handler(reply, nil)
    }

    /// Run the `hearth` binary that ships inside the host application.
    ///
    /// Deliberately not a copy of the rendering logic in Swift. There is one
    /// implementation of what an Ember file looks like, it lives with the
    /// format, and this asks it rather than reimplementing a second opinion
    /// that would drift the first time a format gained a field.
    private static func preview(of url: URL) throws -> Data {
        guard let tool = binary() else {
            return fallback(url, "hearth is missing from the application bundle")
        }

        let process = Process()
        process.executableURL = tool
        process.arguments = ["preview", url.path]
        let out = Pipe()
        let err = Pipe()
        process.standardOutput = out
        process.standardError = err

        do {
            try process.run()
        } catch {
            // A sandboxed extension that cannot spawn a process still has to
            // show something. Saying why beats an empty pane.
            return fallback(url, "could not run hearth: \(error.localizedDescription)")
        }

        // Read before waiting: a preview large enough to fill the pipe buffer
        // would otherwise deadlock against a process that never gets to exit.
        let data = out.fileHandleForReading.readDataToEndOfFile()
        let problem = String(data: err.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)
        process.waitUntilExit()

        guard process.terminationStatus == 0, !data.isEmpty else {
            return fallback(url, problem?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "hearth could not read this file")
        }
        return data
    }

    /// `…/Hearth.app/Contents/PlugIns/HearthQuickLook.appex/Contents/MacOS/`
    /// is where this code runs from, so the binary is four directories up and
    /// back down into Resources. Falling back to an installed `hearth` keeps
    /// the extension working for anyone running it from a development build.
    private static func binary() -> URL? {
        let embedded = Bundle.main.bundleURL      // …/HearthQuickLook.appex
            .deletingLastPathComponent()          // …/PlugIns
            .deletingLastPathComponent()          // …/Contents
            .appendingPathComponent("Resources/hearth")
        if FileManager.default.isExecutableFile(atPath: embedded.path) {
            return embedded
        }
        for path in ["/usr/local/bin/hearth", "\(NSHomeDirectory())/.cargo/bin/hearth"] {
            if FileManager.default.isExecutableFile(atPath: path) {
                return URL(fileURLWithPath: path)
            }
        }
        return nil
    }

    private static func fallback(_ url: URL, _ reason: String) -> Data {
        let name = escape(url.lastPathComponent)
        let why = escape(reason)
        return """
        <!doctype html><html><head><meta charset="utf-8"><style>
        body { font: 13px/1.5 -apple-system, system-ui, sans-serif;
               margin: 0; padding: 22px; color: #2A2230; background: #F3EAD9; }
        @media (prefers-color-scheme: dark) { body { color: #F3EAD9; background: #191420; } }
        h1 { font-size: 15px; margin: 0 0 6px; }
        p { margin: 0; opacity: .7; }
        </style></head><body>
        <h1>\(name)</h1><p>\(why)</p>
        </body></html>
        """.data(using: .utf8) ?? Data()
    }

    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }
}
